### ISSUE TITLE
DependencyResolutionException mvn package

### ISSUE THREAD

**Issue by ysg00** [OHDSI/circe-be#201]
Got this error when trying to install the dependencies:

Failed to collect dependencies at org.ohdsi:circe:jar:1.9.0: Failed to read artifact descriptor for org.ohdsi:circe:jar:1.9.0: Could not transfer artifact org.ohdsi:circe:pom:1.9.0 from/to ohdsi (http://repo.ohdsi.org:8085/nexus/content/repositories/releases): Transfer failed for http://repo.ohdsi.org:8085/nexus/content/repositories/releases/org/ohdsi/circe/1.9.0/circe-1.9.0.pom: Connection reset

Can anyone help

**Comment by chrisknoll** [comment]
I'm not sure where that repo URL came from, but in the pom.xml of this project it states:

```
  <repositories>
    <repository>
      <id>ohdsi</id>
      <name>repo.ohdsi.org</name>
      <url>https://repo.ohdsi.org/nexus/content/groups/public</url>
    </repository>
  </repositories>
```

The URL you are using isn't using https (which is why it fails to connect as of maven 3.6), but it's not clear where that is coming from, other than it's referencing circe.jar 1.9.0 but latest version is 1.11.1.  Is this a build of some other dependency outside of circe-be?
