### ISSUE TITLE
Invalid sql for temp table inclusionRuleCohorts

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/circe-be#24]
## Expected behaviour
When cohort is generated, valid sql should be executed to fill the cohort table.

## Actual behaviour
If a cohort has no 'Additional qualifying inclusion criteria', then the generation fails. There seems to be invalid sql generated for creating the temp table `inclusionRuleCohorts`.

## Steps to reproduce
Environment: Postgresql, commit `2153ccea` of the WebAPI.

In Atlas, create a new cohort and only add a 'Initial Event', e.g. of Any condition. Generate the cohort. Postgres logs the following message: `ERROR:  syntax error at or near "CREATE" at character 109`.

**Comment by chrisknoll** [comment]
@MaximMoinat , this should be fixed in this commit: 3f7f4f900bc01c10adab0397985f45f66c73cdee.  This was part of the 1.3.1 release of Circe, but WebAPI hasn't had an update to point to the new version.  But you can make a local update to your POM.xml file of WebAPI and update the version of circe-be from 1.3.0 to 1.3.1 to see if that fixes your issue.

**Comment by MaximMoinat** [comment]
Great, that works! Next time I'll check the closed issues first :)
